name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: jazzy}
          - {ROS_DISTRO: kilted}
          - {ROS_DISTRO: rolling}
    env:
      ROSDEP_SKIP_KEYS: 'live555 live555_vendor'
      UPSTREAM_WORKSPACE: 'github:fkie/live555_vendor#main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
